"""
Abstract base strategy interface.
All trading strategies must inherit from BaseStrategy.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional, List

import pandas as pd


@dataclass
class Signal:
    """Represents a trade signal generated by a strategy."""

    symbol: str
    security_id: str
    setup_type: str  # '1_pct_setup' or 'ema_pullback'
    entry_price: float
    stop_loss: float
    target1: float
    target2: float
    risk_reward: float
    volume: int
    signal_score: float = 0.0
    timestamp: datetime = field(default_factory=datetime.now)
    candle_index: int = 0
    ema9: float = 0.0
    ema15: float = 0.0
    avg_volume: float = 0.0
    distance_from_ema: float = 0.0
    entry_candle_range: float = 0.0
    notes: str = ""

    # Quality metadata populated by the quality filter
    volume_strength: float = 0.0
    ema_quality: float = 0.0
    pullback_quality: float = 0.0
    breakout_quality: float = 0.0
    momentum_quality: float = 0.0

    # Trade management
    status: str = "pending"  # pending, active, closed
    exit_price: float = 0.0
    exit_time: Optional[datetime] = None
    pnl: float = 0.0
    exit_reason: str = ""
    entry_candle_count: int = 0  # Track candles since entry for breakeven logic

    # Order tracking (populated by order executor)
    order_id: str = ""
    sl_order_id: str = ""
    target_order_id: str = ""
    quantity: int = 0  # Number of shares traded
    is_paper_trade: bool = False



class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    Each strategy scans 5-minute candle data and returns a Signal if conditions are met.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """Human-readable name of the strategy."""
        pass

    @property
    @abstractmethod
    def setup_type(self) -> str:
        """Machine-readable setup type identifier."""
        pass

    @abstractmethod
    def scan(
        self,
        symbol: str,
        security_id: str,
        candles: pd.DataFrame,
        prev_close: float,
    ) -> Optional[Signal]:
        """
        Scan candle data for a setup matching this strategy.

        Args:
            symbol: Trading symbol (e.g., 'RELIANCE').
            security_id: Dhan security ID.
            candles: DataFrame with columns: timestamp, open, high, low, close, volume.
                     Must be 5-minute intraday candles for today.
            prev_close: Previous day's closing price.

        Returns:
            Signal object if a valid setup is found, None otherwise.
        """
        pass

    def _validate_candles(self, candles: pd.DataFrame) -> bool:
        """Validate that the candle DataFrame has required columns and minimum data."""
        required_cols = {"timestamp", "open", "high", "low", "close", "volume"}
        if not required_cols.issubset(candles.columns):
            return False
        if len(candles) < 2:
            return False
        return True
